---
title: "Week6 Final Submitted"
author: "Rajwant Mishra"
date: "March 9, 2019"
output: 
html_document:
      theme: yeti  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<style>
body {
    margin: 0;            /* Reset default margin */
}
iframe {
    display: block;       /* iframes are inline by default */
    background: #000;
    border: none;         /* Reset default border */
    height: 100vh;        /* Viewport-relative units */
    width: 100vw;
}
.container-fluid.main-container {
    max-width: 99%;
}
</style>

## Project For week 6 (3 Dataset)



### Analysis Disability Data

<details>
<summary>
<b><i>Project 1</i></b>

Please give it time to load .

Data is from US disability, it list number of applications being submitted from online and offline . Objective is to find that if Online service has helped Gov. to get more application through online mode. * Data has lots of problem + Data is wide by Month, AND also Fiscal Year may Not equal to same year.

(it opens in new window)
<a target="_blank" href="http://rpubs.com/Rajwantmishra/week6_607_p2of3">
Direct Link</a>
</summary>
<iframe src="http://rpubs.com/Rajwantmishra/week6_607_p2of3" width="100%" height="100%"></iframe>

</details>

### Analysis using Entropy 
<details>
<summary>
<b><i>Project 2</i></b>
Please give it time to load .

This dataset of the heart patient.

(it opens in new window)
<a target="_blank" href="http://rpubs.com/Rajwantmishra/week6_607_p3of3">
Direct Link</a>
</summary>
<iframe src="http://rpubs.com/Rajwantmishra/week6_607_p3of3" width="100%" height="100%"></iframe>

</details>

### With Shiny App for countries 
<details>
<summary>
<b><i>Project 3</i></b>
Please give it time to load.

There are several challenges of this untidy dataset steel imports.

1 .multiple layers of headers: year -> month -> quantity/value
2. nonuniform values: some values are sums of other values


(it opens in new window)
<a target="_blank" href="https://rajwantmishra.shinyapps.io/Week6_P1/">
Direct Link</a>
</summary>
<iframe src="https://rajwantmishra.shinyapps.io/Week6_P1/" width="100%" height="100%"></iframe>

</details>


